// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Iliya Brook",
            "email": "iliyabrook1987@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/getBreeds": {
            "get": {
                "description": "Returns a list of all dog breeds.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "breeds"
                ],
                "responses": {
                    "200": {
                        "description": "List of all dog breeds",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/sharable.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/getDogs": {
            "get": {
                "description": "Returns a list of dogs by breed name. If the breed name is partially matched, similar results are returned.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dogs"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Breed name",
                        "name": "breed",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "\"live_vFE31lne23gsyVcR9QYhgMySY7TnESm3Tj7jWrJtcSJeY7KgIkXNPJmXH8GKMlGd\"",
                        "description": "API key required to access this endpoint",
                        "name": "x-api-key",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of matching dogs",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/sharable.DogResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Breed name is required",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "sharable.DogResponse": {
            "type": "object",
            "properties": {
                "bred_for": {
                    "type": "string"
                },
                "breed_group": {
                    "type": "string"
                },
                "country_code": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "height": {
                    "type": "object",
                    "properties": {
                        "imperial": {
                            "type": "string"
                        },
                        "metric": {
                            "type": "string"
                        }
                    }
                },
                "history": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "object",
                    "properties": {
                        "height": {
                            "type": "integer"
                        },
                        "id": {
                            "type": "string"
                        },
                        "url": {
                            "type": "string"
                        },
                        "width": {
                            "type": "integer"
                        }
                    }
                },
                "life_span": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "reference_image_id": {
                    "type": "string"
                },
                "temperament": {
                    "type": "string"
                },
                "weight": {
                    "type": "object",
                    "properties": {
                        "imperial": {
                            "type": "string"
                        },
                        "metric": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "sharable.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Dog Breeds API",
	Description:      "Dog Breeds API project from golang ninja course",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
