definitions:
  sharable.DogResponse:
    properties:
      bred_for:
        type: string
      breed_group:
        type: string
      country_code:
        type: string
      description:
        type: string
      height:
        properties:
          imperial:
            type: string
          metric:
            type: string
        type: object
      history:
        type: string
      id:
        type: integer
      image:
        properties:
          height:
            type: integer
          id:
            type: string
          url:
            type: string
          width:
            type: integer
        type: object
      life_span:
        type: string
      name:
        type: string
      origin:
        type: string
      reference_image_id:
        type: string
      temperament:
        type: string
      weight:
        properties:
          imperial:
            type: string
          metric:
            type: string
        type: object
    type: object
  sharable.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
info:
  contact:
    email: iliyabrook1987@gmail.com
    name: Iliya Brook
  description: Dog Breeds API project from golang ninja course
  title: Dog Breeds API
  version: "1.0"
paths:
  /getBreeds:
    get:
      description: Returns a list of all dog breeds.
      produces:
      - application/json
      responses:
        "200":
          description: List of all dog breeds
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/sharable.ErrorResponse'
      tags:
      - breeds
  /getDogs:
    get:
      consumes:
      - application/json
      description: Returns a list of dogs by breed name. If the breed name is partially
        matched, similar results are returned.
      parameters:
      - description: Breed name
        in: query
        name: breed
        required: true
        type: string
      - default: '"live_vFE31lne23gsyVcR9QYhgMySY7TnESm3Tj7jWrJtcSJeY7KgIkXNPJmXH8GKMlGd"'
        description: API key required to access this endpoint
        in: header
        name: x-api-key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of matching dogs
          schema:
            items:
              $ref: '#/definitions/sharable.DogResponse'
            type: array
        "400":
          description: Breed name is required
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      tags:
      - dogs
swagger: "2.0"
